### ISSUE TITLE
new filter option `category: ` for points of interest and tours

### ISSUE THREAD

**Issue by donni106** [ikuseiGmbH/smart-village-app-mainserver#113]
we want to filter points of interest and tours on categories.
so we need queries for points of interest and tours, that understand a category variable.

example: `pointsOfInterest(category: 'Hotels')` should return only all points of interest with category name 'Hotel'

is it possible to allow name and id of a category at the same time, so a user can query for `category: 'Hotel'` or `category: 12`. the server than makes a `where(name: category).first` or `where(id: category).first`?

**Comment by donni106** [comment]
@acousma82 kannst du dich bitte noch zu der angestoßenen offenen Diskussion äußern?!

**Comment by acousma82** [comment]
Ja Würde ich dann mit ner einfachen if else logik in der entsprechenden Methode lösen. Oder alternativ, was ich persönlich besser finde und was sauberer ist: einfach zwei optionen daraus machen: category_name: <name> und category_id: <id>

**Comment by donni106** [comment]
Und was passiert dann für den Fall, dass jemand beide Optionen angibt? Werden dann beide berücksichtigt? Hat einer davon Prio?
