### ISSUE TITLE
Deactivate gitlab-ci in master?

### ISSUE THREAD

**Issue by donni106** [ikuseiGmbH/smart-village-app-mainserver#147]
Können wir die stages auskommentieren im master @marcometz?

https://github.com/ikuseiGmbH/smart-village-app-mainserver/blob/4b6a9d41aca657ce2f9fc9fd3942d69311dfca18/.gitlab-ci.yml#L11-L14

Die beiden Branch-Angaben in den stages müssten auch zumindest auf `master` angepasst werden:

https://github.com/ikuseiGmbH/smart-village-app-mainserver/blob/4b6a9d41aca657ce2f9fc9fd3942d69311dfca18/.gitlab-ci.yml#L36-L37

https://github.com/ikuseiGmbH/smart-village-app-mainserver/blob/4b6a9d41aca657ce2f9fc9fd3942d69311dfca18/.gitlab-ci.yml#L51-L52

**Comment by marcometz** [comment]
Auskommentieren wäre vermutlich eine Lösung **oder** den eindeutigen Verweis auf einen Git Branch, den es nicht gibt.

Nur **master** sollte da auf keinen fall stehen, ansonsten wird jeder commit dort hin versucht auch zu deployen.

**Comment by donni106** [comment]
> eindeutigen Verweis auf einen Git Branch, den es nicht gibt

So ist es jetzt, oder? Da merkt GitLab dann, dass es etwas nicht gibt und bricht ab/hört auf?
