### ISSUE TITLE
In der Query "genericItems" fehlen mir noch die folgenden Filtermöglichkeiten:

### ISSUE THREAD

**Issue by pwilimzig** [ikuseiGmbH/smart-village-app-mainserver#191]
In der Query "genericItems" fehlen mir noch die folgenden Filtermöglichkeiten: 

- dataProvider: DataPovider
- dataProviderID: ID
- categoryId: ID
- contentType: Type
- externalId: String

_Originally posted by @pwilimzig in https://github.com/ikuseiGmbH/smart-village-app-mainserver/issues/190#issuecomment-781266010_

**Comment by donni106** [comment]
`genericType` statt `contentType`. habe es im kommentar im PR bereits richtig hineingeschrieben

**Comment by marcometz** [comment]
> `genericType` statt `contentType`. habe es im kommentar im PR bereits richtig hineingeschrieben

ContentType == GenericType

Das ist der Typ des GenericItems. Was für Inhalte(Content) das GenericItem hat ist davon unabhängig und im Zweifel auch nicht eindeutige. Ein Job kann ja viele Contents habe: Beschreibung, Laufzeiten, Aufgaben, Adressen....

**Comment by donni106** [comment]
> > `genericType` statt `contentType`. habe es im kommentar im PR bereits richtig hineingeschrieben
> 
> ContentType == GenericType
> 
> Das ist der Typ des GenericItems. Was für Inhalte(Content) das GenericItem hat ist davon unabhängig und im Zweifel auch nicht eindeutige. Ein Job kann ja viele Contents habe: Beschreibung, Laufzeiten, Aufgaben, Adressen....

genau, deswegen muss es im code auch `genericType` sein anstatt `contentType`

**Comment by marcometz** [comment]
die Filter sind nun hinzugefügt: https://github.com/ikuseiGmbH/smart-village-app-mainserver/pull/190/commits/bc7856e67c753400aa9db567d26eb2d71e87eab3

**Comment by pwilimzig** [comment]
Sorry für die Verwirrung. "ContentType" kam noch aus der alten Liste. "GenericType" ist korrekt.
