### ISSUE TITLE
GenericItem kann keine Categories verarbeiten

### ISSUE THREAD

**Issue by pwilimzig** [ikuseiGmbH/smart-village-app-mainserver#193]
In der Mutation createGenericItem kommt ein Fehler, wenn Categories erstellt werden sollen.

**Geht:** 
```
mutation {
  createGenericItem (
    title: "Test"
  ) {
   id
   title
 }
}
```
 

**Geht nicht:**
```
mutation {
  createGenericItem (
    title: "Test"
    categories:[{ name: "Test" }]
  ) {
   id
   title
 }
}
```

**Comment by donni106** [comment]
zur Info, hat vermutlich damit zu tun, was hier im PR kommentiert wurde: https://github.com/ikuseiGmbH/smart-village-app-mainserver/pull/190#discussion_r579145428

**Comment by marcometz** [comment]
fixed im PR https://github.com/ikuseiGmbH/smart-village-app-mainserver/pull/190
