### ISSUE TITLE
Serverseitige Destroy Mutation für Jobs und Anzeigen anlegen

### ISSUE THREAD

**Issue by theresasteinmetz** [ikuseiGmbH/smart-village-app-mainserver#195]
Fehlende Destroy Mutation für Jobs und Anzeigen anlegen

![Bildschirmfoto 2021-02-24 um 13 41 07](https://user-images.githubusercontent.com/61157877/109002143-1aba5580-76a6-11eb-8061-87883afffc98.png)
<img width="328" alt="Bildschirmfoto 2021-02-24 um 13 42 40" src="https://user-images.githubusercontent.com/61157877/109002194-2c9bf880-76a6-11eb-915b-8dfdf785dfb0.png">

**Comment by donni106** [comment]
fb8e370a93fdde3630ebfb71d1f27fa868bfbad8 reicht wohl noch nicht

**Comment by marcometz** [comment]
reicht, lokal und auf dem StagingServer getestet

**Comment by pwilimzig** [comment]
@theresasteinmetz Ich hatte einen ähnlichen Fehler und bei mir lag es an der Schreibweise von "GenericItem". Versuch es mal mit einem großen G
