### ISSUE TITLE
mutation destroyRecord does not work for genericItems

### ISSUE THREAD

**Issue by pwilimzig** [ikuseiGmbH/smart-village-app-mainserver#196]
```
mutation {
    destroyRecord(
    id: 31
    recordType: "genericItem"
  ) {
    id
    status
    statusCode
  }
}
```

results to

```
{
  "data": {
    "destroyRecord": {
      "id": null,
      "status": "Access not permitted",
      "statusCode": 403
    }
  }
}
```

**Comment by donni106** [comment]
sollte mit #195 eigentlich ermöglicht worden sein. wird authentifizierung mitgeschickt?

**Comment by marcometz** [comment]
Auf welchem Server wurde hier versucht zu löschen? Auf dem Int/Dev System gibt es keinen Datensatz mit der ID 31, der gelöscht werden könnte. @pwilimzig

**Comment by pwilimzig** [comment]
Der Fehler lag woanders: Es muss 'recordType: "GenericItem"' mit großem G heißen. Kaum macht man es richtig, geht es auch :(
