### ISSUE TITLE
Rename openingtimedate in openingtimedates

### ISSUE THREAD

**Issue by marcometz** [ikuseiGmbH/smart-village-app-mainserver#29]
in JSON for `OpeningHours`

**Comment by acousma82** [comment]
@marcometz Please specify and write why this change is necessary.

**Comment by acousma82** [comment]
@Marco Warum soll das umbenannt werden

**Comment by marcometz** [comment]
weil es mehrere Daten sind und nicht nur ein einzelner Termin

**Comment by acousma82** [comment]
Aber openinhours heißt auf Deutsch Öffnungszeiten. Sowohl im deutschen als auch im Englischen beschreibt man damit mehrere Öffnungszeiten. openingtimedate tauch in keinem JSon der MainServerApp auf. Auf was genau beziehst Du Dich also. Auf die Api Doku ?

**Comment by donni106** [comment]
Ich kann ebenfalls keine Treffer zu `openingtimedate` vermelden.
