### ISSUE TITLE
[GraphQL queries] ability to limit the amount of data and order them

### ISSUE THREAD

**Issue by donni106** [ikuseiGmbH/smart-village-app-mainserver#36]
In the mobile app, we do not always want all data of a resource. Therefore we need the ability to query with arguments to limit and order data that were fetched.

In [one part of a tutorial](https://learn.hasura.io/graphql/react-native/intro-to-graphql/2-fetching-data-queries#Multiple%20arguments%20on%20multiple%20fields:%20Fetch%201%20user%20and%205%20most%20recent%20todos%20for%20each%20user) I found a nice example with exactly the needed queries.

Simplified example queries for our app:

**limit**

```
query {
  point_of_interests (limit: 10) {
    id
    name
  }
}
```

**order**

```
query {
  point_of_interests (order_by: {created_at: desc}) {
    id
    name
  }
}
```

- possible order fields should be like: `created_at`, `updated_at`, `id`, `name`
- order statements: `desc`, `asc`

**or combined**

```
query {
  point_of_interests (order_by: {created_at: desc}, limit: 5) {
    id
    name
  }
}
```

Please make **limit** and **order_by** arguments available for every main resource.
If no argument is given, the default should be all data ordered by `id` or `created_at` in ascending order.

**Comment by acousma82** [comment]
@donni106 Setze ich gerne um.

**Comment by acousma82** [comment]
eine bessere umsetung dieses tasks findet gerade hier statt: #44
