### ISSUE TITLE
Create graphql mutations for all main resources

### ISSUE THREAD

**Issue by acousma82** [ikuseiGmbH/smart-village-app-mainserver#46]
Points of Interest, Event records, News Items and Tours need to be created via the graphql Api. To implement that we need to specify mutations and resolve them via the ruby graphql server.

**Comment by acousma82** [comment]
Erledigt für Resource POI

**Comment by donni106** [comment]
Wie ist hier der Stand @acousma82?

**Comment by acousma82** [comment]
ist fertig
