### ISSUE TITLE
Turn off CSRF token validation

### ISSUE THREAD

**Issue by donni106** [ikuseiGmbH/smart-village-app-mainserver#47]
To lt the mobile app communicate with the API endpoint for GraphQL we need to turn off CSRF token validation.

I got this error:

```
Processing by GraphqlController#execute as */*
  Parameters: {"operationName"=>nil, "variables"=>{}, "query"=>"{\n  tours {\n    id\n  }\n}\n", "graphql"=>{"operationName"=>nil, "variables"=>{}, "query"=>"{\n  tours {\n    id\n  }\n}\n"}}
Can't verify CSRF token authenticity.
Completed 422 Unprocessable Entity in 0ms (ActiveRecord: 0.0ms)

ActionController::InvalidAuthenticityToken (ActionController::InvalidAuthenticityToken):
```

It seems to be the common way for API controller.
Solution found here: https://stackoverflow.com/questions/35181340/rails-cant-verify-csrf-token-authenticity-when-making-a-post-request

Need to add this:
```
protect_from_forgery with: :null_session
```

here:
https://github.com/ikuseiGmbH/smart-village-app-mainserver/blob/2518083c4a9a23814dd689383dcfa39bb63dc660/app/controllers/graphql_controller.rb#L3

**Comment by marcometz** [comment]
da die GraphQl APi eine öffentliche Api sein soll (die per OAuth verifiziert ist) können wir hier ohne Sorge auf die Sicherheit eines CRSF Tokens verzichten und `protect_from_forgery with: :null_session`dauerhaft in dem Controller integrieren

**Comment by marcometz** [comment]
bitte nur den graphQL Controller ungesichert lassen (protect_from_forgery with: :null_session)
