### ISSUE TITLE
Doubletten check und update Funktion der Records

### ISSUE THREAD

**Issue by marcometz** [ikuseiGmbH/smart-village-app-mainserver#58]
Zu klären ist wo die Doublettenprüfung stattfinden wird und wie ein Update auszusehen hat

**Comment by donni106** [comment]
Diese Daten sind keine Dubletten, sondern Updates. Die Inhalte der drei Einträge sind nicht identisch.

![IMG_C3BF0309B3B2-1](https://user-images.githubusercontent.com/1942953/60037278-6cc8fd80-96b1-11e9-8e28-9c831d95c881.jpeg)

Wie gehen wir damit um?

**Comment by acousma82** [comment]
@marcometz Das sollten wir sobald wie möglich diskutieren. Zur Zeit gibt es noch keine explizite update actions.

**Comment by pwilimzig** [comment]
@acousma82 Bitte versuch hier eine Lösung zu finden, möglichst ohne Rene und Marco allzu sehr einzuspannen. Außerdem wird heute wohl ein Artikel kommen, der dann gleich wieder gelöscht wird. Dann haben wir für diese Situation dann auch gleich einen Testfall.

**Comment by marcometz** [comment]
Meiner Meinung nach haben wir bereits einen Doubletten Check. Die News liefern angeblich eine ID mit. Zu prüfen wäre ob die ID auch im Check verwendet wird (NUR BEI DEN NEWS).

Ein Update sieht bisher so aus, dass wird den alten Datensatz löschen und den neuen Importiert (So wie im CMS)

**Comment by marcometz** [comment]
Das gezielte Löschen einzelner Beiträge funktioniert dann dabei über die gleiche Aktion im MainAppServer (Löschen eines Records). Was hier noch fehlt ist im MaZ Importer der RestEndpunkt zum erkennen eines Löschauftrages von der Max und das Weiterschleifen dieses Requests zum MainApppServer. Details dazu finden sin im Confluence: https://confluence.communicatio.com/display/SVA/2019-06-18+Besprechungsnotizen

**Comment by donni106** [comment]
Ist das durch?

**Comment by acousma82** [comment]
Ja, der Pr dazu wurde ja gemergt
