### ISSUE TITLE
Falsche Datumsangaben für Events?

### ISSUE THREAD

**Issue by donni106** [ikuseiGmbH/smart-village-app-mainserver#70]
Wenn wir bei Events die `dates` abfragen, erhalten wir folgendes:

```
"dates": [
  {
    "dateStart": "0014-09-18",
    "dateEnd": "0026-01-20",
    "timeStart": "2000-01-01 06:01:00 UTC",
    "timeEnd": "2000-01-01 15:14:00 UTC"
  }
],
```

1. die Jahreszahlen sind nicht korrekt
2. ich hätte bei `timeStart` und `timeEnd` reine Zeitangaben erwartet, statt vollständige Datumsangaben
2.1. `2000-01-01` bei Zeitangaben sind vermutlich wegen der Dummydaten, aber bitte prüfen, dass dort die richtigen Daten durchkommen

Bitte beheben. Danke.

**Comment by donni106** [comment]
zwei Einträge wären ideal mit vollständigen Werten:

```
"dates": [
  {
    "end": "2019-12-14 01:00:00 +0100",
    "start": "2019-12-13 22:00:00 +0100"
  }
] 
```

**Comment by donni106** [comment]
Wieso nicht nur so, wie im letzte Kommentar als Vorschlag von mir @marcometz? War es einfacher nur die Formatierung zu machen? Sind die Times jetzt schon in der richtigen Zeitzone zum darstellen?

**Comment by marcometz** [comment]
```
"dates": [
          {
            "id": "7",
            "dateStart": "1998-06-18",
            "dateEnd": "2012-02-20",
            "timeStart": "23:25",
            "timeEnd": "21:30"
          }
        ]
```

Die Zusammenfassung der Daten zu jeweils einer Zeile Datum Mit Uhrzeit geht leider nicht. Es kommt vor das Wir nur eine Uhrzeit haben oder nur ein Datum. wenn wir dies in einem DateTimeObject behandeln müsste man ein FallbackDatum und eine FallbackUhrzeit definieren die "nil" bedeutet

**Comment by donni106** [comment]
das gleiche bitte noch bei POI-openinghours @marcometz

**Comment by donni106** [comment]
Außerdem ist `weekday` immer `null` scheinbar. Wenn wir aber ein Datum haben, ist ja auch der Wochentag klar. Der könnte dann also mit übermittelt werden.

```
{
    "dateEnd": "2019-12-08",
    "dateStart": "2019-12-08",
    "timeEnd": "18:00",
    "timeStart": "14:00",
    "timeDescription": "",
    "useOnlyTimeDescription": "false",
    "weekday": null
  }
```

**Comment by donni106** [comment]
Ok, für `POIs openingHours` gibt es nun die PR #91.

Wie verfahren wir mit den `weekday`s? Sollen die in jedem Fall `null` bleiben?

**Comment by acousma82** [comment]
die weekdays werden nur gesetzt wenn es ein sich wiederholender event ist, ansonsten ist der weekday null.
