### ISSUE TITLE
Sortierung der Events nach Event-Datum

### ISSUE THREAD

**Issue by donni106** [ikuseiGmbH/smart-village-app-mainserver#86]
Events müssen nach ihrem Event Datum sortiert angezeigt werden.
Diese Möglichkeit der Sortierung gibt es scheinbar noch nicht.

https://github.com/ikuseiGmbH/smart-village-app-mainserver/blob/master/app/graphql/resolvers/event_records_search.rb

`created_at`, `updated_at` und `title` sind bei Events nicht hilfreich.

**Bitte mit hoher Prio angehen!**

Außerdem ist bzgl. Events auch noch #70 dringend abzuschließen.

**Comment by acousma82** [comment]
Das ist natürlich nicht so einfach umsetzbar, da die event dates ein anderes model sind. was macht man zum beispiel, wenn ein event mehrere dates hat oder ein event ein sich wiederholender Event ist. Ich bin der Meinung es wäre am Besten einfach einen eventsdatumfilter bei dir einzubauen, nach denen der user sich dann die events nach veranstaltungsdatum sortieren kann. Was meinst Du?

**Comment by marcometz** [comment]
Workflow für chronologische Veranstaltungsliste:

Backend (MainServer):
- mehrere EventDates eines Events werden aufsteigend Sortiert
- das jüngste/erste Eventdatum welches in der Zukunft liegt wird für die Sortierung verwendet
- dieses Sortierdatum kann über ein virtuelles Attribute :list_date über graphql abgefragt werden und im Frontend für die Darstellung verwendet werden
- :list_date wird ein weiterer Sortierparameter wie :created_at und :updated_at
- die Wiederkehrende Optionen werden erstmal ignoriert

Frontend (App):
- Die Einträge werden über GraphQL sortiert angefragt über :list_date
- Die Einträge in der Liste werden Sortiert dargestellt
- Das Darstellungsdatum ist ebenfalls :list_date
- auf der "Show-Seite" werden dann erst alle Eventdaten angezeigt
- die Wiederkehrenden Optionen werden eventuell dargestellt
