### ISSUE TITLE
1 Destroy Mutation für alle Main Ressourcen

### ISSUE THREAD

**Issue by marcometz** [ikuseiGmbH/smart-village-app-mainserver#94]
Es müssen einzelne Records von :events, :tour, news_item und :poi gelöscht werden können.
Dabei reicht mir eine `deleteRecord` Mutation, der man eine ID und ein RecordType übergibt.

{
mutation deleteRecord(id: 1, record_type: "News")
}

Wichtig beim Löschen ist, dass die Abhängigkeiten nach unten ebenfalls gelöscht werden (`dependent: :destroy/:delete`), wenn sie nicht mehr von anderen Ressourcen verwendet werden. Große Ausnahme bildet hier der **DataProvider**, der darf auf keinen Fall gelöscht werden!!!!!!

**Comment by acousma82** [comment]
das mit dem record_type als argument wird nicht funktionieren, da man bei graphql ruby immer den objekt typen in den muttions/resolvern eindeutig angeben muss.

**Comment by marcometz** [comment]
dann mach ich das
